import type { IToastCall } from './types';

const ToastCall: IToastCall = {
  createBlogSuccess: (description) => ({
    title: 'สร้างบทความใหม่สำเร็จ',
    description,
    status: 'success',
    duration: 5000,
    isClosable: true,
    position: 'bottom-right',
  }),
  createBlogFail: (description) => ({
    title: 'สร้างบทความใหม่ไม่สำเร็จ',
    description,
    status: 'error',
    duration: 5000,
    isClosable: true,
    position: 'bottom-right',
  }),
  createBlogEmpty: () => ({
    title: 'สร้างบทความใหม่ไม่สำเร็จ',
    description: 'เกิดข้อผิดพลาดขึ้นในบทความของคุณ',
    status: 'error',
    duration: 5000,
    isClosable: true,
    position: 'top',
  }),
  editBlogSuccess: (description) => ({
    title: 'แก้ไขบทความสำเร็จ',
    description,
    status: 'success',
    duration: 5000,
    isClosable: true,
    position: 'bottom-right',
  }),
  editBlogFail: (description) => ({
    title: 'แก้ไขบทความไม่สำเร็จ',
    description,
    status: 'error',
    duration: 5000,
    isClosable: true,
    position: 'top',
  }),
  editBlogEmpty: () => ({
    title: 'แก้ไขบทความไม่สำเร็จ',
    description: 'โปรดตรวจสอบบทความก่อนทำการแก้ไขอีกครั้ง',
    status: 'error',
    duration: 5000,
    isClosable: true,
    position: 'top',
  }),
  publishBlogStatus: () => ({
    title: 'เปลี่ยนสถานะบทความสำเร็จ',
    description:
      'บทความได้ถูกเปลี่ยนเป็นสาธารณะ ผู้อ่านสามารถเห็นบทความนี้ในเว็บไซต์ชาญชรา',
    status: 'success',
    duration: 5000,
    isClosable: true,
    position: 'bottom-right',
  }),
  draftBlogStatus: () => ({
    title: 'เปลี่ยนสถานะบทความสำเร็จ',
    description:
      'บทความได้ถูกเปลี่ยนเป็นแบบร่าง ผู้อ่านจะไม่สามารถเห็นบทความนี้ในเว็บไซต์ชาญชรา',
    status: 'warning',
    duration: 5000,
    isClosable: true,
    position: 'bottom-right',
  }),
  changeBlogStatusFail: () => ({
    title: 'เปลี่ยนสถานะบทความไม่สำเร็จ',
    description: 'เกิดข้อผิดพลาดในการเปลี่ยนสถานะของบทความ',
    status: 'error',
    duration: 5000,
    isClosable: true,
    position: 'top',
  }),
  deleteBlogSuccess: () => ({
    title: 'ลบบทความสำเร็จ',
    description: 'บทความได้ถูกลบ',
    status: 'success',
    duration: 5000,
    isClosable: true,
    position: 'bottom-right',
  }),
  deleteBlogFail: () => ({
    title: 'ลบบทความไม่สำเร็จ',
    description: 'เกิดข้อผิดพลาดในการลบบทความ',
    status: 'success',
    duration: 5000,
    isClosable: true,
    position: 'bottom-right',
  }),
  createTagSuccess: (description) => ({
    title: 'สร้างหมวดหมู่สำเร็จ',
    description,
    status: 'success',
    duration: 5000,
    isClosable: true,
    position: 'bottom-right',
  }),
  deleteTagSuccess: (description) => ({
    title: 'ลบหมวดหมู่สำเร็จ',
    description,
    status: 'success',
    duration: 5000,
    isClosable: true,
    position: 'bottom-right',
  }),
  addUserSuccess: (description) => ({
    title: 'เพิ่มผู้ใช้สำเร็จ',
    description,
    status: 'success',
    duration: 5000,
    isClosable: true,
    position: 'bottom-right',
  }),
  addUserFailed: (description) => ({
    title: 'เพิ่มผู้ใช้ไม่สำเร็จ',
    description,
    status: 'error',
    duration: 5000,
    isClosable: true,
    position: 'bottom-right',
  }),
  deleteUserSuccess: () => ({
    title: 'ลบผู้ใช้สำเร็จ',
    description: 'ลบผู้ใช้สำเร็จ',
    status: 'success',
    duration: 5000,
    isClosable: true,
    position: 'bottom-right',
  }),
  deleteUserFailed: (description) => ({
    title: 'ลบผู้ใช้ไม่สำเร็จ',
    description,
    status: 'error',
    duration: 5000,
    isClosable: true,
    position: 'bottom-right',
  }),
  renameSuccess: (description) => ({
    title: 'เปลี่ยนชื่อผู้ใช้สำเร็จ',
    description,
    status: 'success',
    duration: 5000,
    isClosable: true,
    position: 'bottom-right',
  }),
  renameFailed: (description) => ({
    title: 'เปลี่ยนชื่อผู้ใช้ไม่สำเร็จ',
    description,
    status: 'error',
    duration: 5000,
    isClosable: true,
    position: 'bottom-right',
  }),
  renameLength: () => ({
    title: 'เปลี่ยนชื่อผู้ใช้ไม่สำเร็จ',
    description: 'ชื่อผู้ใช้ควรมีความยาวมากกว่า 5 ตัวอักษร',
    status: 'error',
    duration: 5000,
    isClosable: true,
    position: 'bottom-right',
  }),
  sessionTimeOut: () => ({
    title: 'เซสชั่นหมดอายุ',
    description: 'กรุณาเข้าสู่ระบบใหม่อีกครั้ง',
    status: 'error',
    duration: 5000,
    isClosable: true,
    position: 'top',
  }),
  uploadImageFail: () => ({
    title: 'ไม่สามารถอัพโหลดรูปภาพได้',
    description: 'เกิดปัญหาขึ้นระหว่างการอัพโหลดรูปภาพ',
    status: 'error',
    duration: 5000,
    isClosable: true,
    position: 'bottom-right',
  }),
  createAnnouncementSuccess: (description) => ({
    title: 'สร้างประกาศใหม่สำเร็จ',
    description,
    status: 'success',
    duration: 5000,
    isClosable: true,
    position: 'bottom-right',
  }),
};

export default ToastCall;
